/**                                          
 * @ingroup gen_cfw                          
 *                                           
 * Body file for module implementing procedure TestCase2  
 *                                           
 * @note This file was generated on  2023-10-03 22:34:00.619040
 * @author Automatically generated by CORDET Editor Code Generator
 * @copyright P&P Software GmbH
 */                                          

#include <TestCase2.h>

/** The current procedure node */
static eTestCase2Nodes_t curNode = FwPrTestCase2Stopped;

unsigned int FwPrTestCase2IsStarted() {
    return curNode != eTestCase2Stopped;
}

eTestCase2Nodes_t FwPrTestCase2GetCurNode() {
    return curNode;
}

void FwPrTestCase2Start() {
    if (curNode != eTestCase2Stopped)
        return;
    curNode = eTestCase2Init;
}

void FwPrTestCase2Stop() {
    if (curNode == eTestCase2Stopped)
        return;
    curNode = eTestCase2Stopped;
}

void FwPrTestCase2Execute() {
    if (curNode == eTestCase2Stopped)
        return;
    while (1) {
        if (curNode == eTestCase2Init) {
            if (FwPrTestCase2Decision1N2() == 1) {
                curNode = eTestCase2N2;
                FwPrTestCase2N2();
                curNode = eTestCase2N4;
                FwPrTestCase2N4();
                curNode = eTestCase2Stopped;
                return;
            } else if (FwPrTestCase2Decision1Decision2() == 1) {
                if (FwPrTestCase2Decision2N1() == 1) {
                    curNode = eTestCase2N1;
                    FwPrTestCase2N1();
                    curNode = eTestCase2Stopped;
                    return;
                } else  {
                    curNode = eTestCase2N4;
                    FwPrTestCase2N4();
                    curNode = eTestCase2Stopped;
                    return;
                }
            } else  {
                FwPrTestCase2N3();
            }
        }
        if (curNode == eTestCase2N3) {
            if (FwPrTestCase2N3N5() == 0) {
                return
            curNode = eTestCase2N5;
            FwPrTestCase2N5();
            if (FwPrTestCase2Decision2N1() == 1) {
                curNode = eTestCase2N1;
                FwPrTestCase2N1();
                curNode = eTestCase2Stopped;
                return;
            } else  {
                curNode = eTestCase2N4;
                FwPrTestCase2N4();
                curNode = eTestCase2Stopped;
                return;
            }
            }
        }
    }
}

