/**                                          
 * The functions declared in this file allow the user to control the operation
 * of the FW Profile procedure TestCase2.The following operations can be
 * performed on the procedure: (a) Start, stop and execute the procedure (b)
 * Query the procedure for its start/stop state and for its current node  
 *                                           
 * @note This file was generated on  2023-10-03 22:34:00.618965
 * @author Automatically generated by FW Profile Code Generator
 * @copyright P&P Software GmbH
 */                                          
#ifndef FWPRTESTCASE2_H_
#define FWPRTESTCASE2_H_

/** Enumerated type for the procedure nodes */
typedef enum {
    eTestCase2Stopped = 0;
    eTestCase2N1 = 1;
    eTestCase2N2 = 2;
    eTestCase2N3 = 3;
    eTestCase2N4 = 4;
    eTestCase2N5 = 5;
} eTestCase2Nodes_t;

/** Function to start procedure TestCase2 */
void FwPrTestCase2Start();

/** Function to stop procedure TestCase2 */
void FwPrTestCase2Stop();

/** Function to execute procedure TestCase2 */
void FwPrTestCase2Exec();

/**
 * Check the current state of procedure TestCase2
 * @return 0 if the procedure is not started; 1 otherwise
 */
unsigned int FwPrTestCase2IsStarted();

/**
 * Get the current node of the procedure TestCase2
 * @return -1 if the procedure is stopped; otherwise the current node
 */
eTestCase2Nodes_tTestCase2GetCurNode();

#endif /* FWPRTESTCASE2_H_ */
