/**                                          
 * The functions in this file implement the actions and guards of the FW Profile
 * procedure of TestCase2.The user is responsible for providing a C body file
 * which implements all the functions declared in this header file.  
 *                                           
 * @note This file was generated on  2023-10-03 22:34:00.618835
 * @author Automatically generated by FW Profile Code Generator
 * @copyright P&P Software GmbH
 */                                          
#ifndef FWPRTESTCASE2USER_H_
#define FWPRTESTCASE2USER_H_

/**
 * Function implementing the action for node N1
 * Node N1 Action
 */
void FwPrTestCase2N1();

/**
 * Function implementing the action for node N2
 * Node N2 Action
 */
void FwPrTestCase2N2();

/**
 * Function implementing the action for node N3
 * Node N3 Action
 */
void FwPrTestCase2N3();

/**
 * Function implementing the action for node N4
 * Node N4 Action
 */
void FwPrTestCase2N4();

/**
 * Function implementing the action for node N5
 * Node N5 Action
 */
void FwPrTestCase2N5();

/**
 * Function implementing the guard from Decision1 to N2
 * Flag_1
 */
void FwPrTestCase2TestCase2Decision1ToN2();

/**
 * Function implementing the guard from N3 to N5
 * Wait Condition 1
 */
void FwPrTestCase2TestCase2N3ToN5();

/**
 * Function implementing the guard from Decision1 to Decision2
 * Flag_2
 */
void FwPrTestCase2TestCase2Decision1ToDecision2();

/**
 * Function implementing the guard from Decision2 to N1
 * Flag_3
 */
void FwPrTestCase2TestCase2Decision2ToN1();

#endif /* FWPRTESTCASE2USER_H_ */
